# Change these first
owner: King-Ulee # Your GitHub organization or username, where this repository lives
repo: Status-Page-Advanced # The name of this repository

sites:
  - name: Kingulee.com
    url: https://www.kingulee.com/
    icon: https://kingulee.com/images/logo.png
  - name: Kingulee.com/belajar
    url: https://www.kingulee.com/belajar/
    icon: https://kingulee.com/images/logo.png
  - name: Kingulee.com/artikel
    url: https://www.kingulee.com/artikel/
    icon: https://kingulee.com/images/logo.png
  - name: Kingulee.com/lainnya
    url: https://www.kingulee.com/lainnya/
    icon: https://kingulee.com/images/logo.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: kingulee.my.id
  # baseUrl: /Status-Page-Advanced
  faviconSvg: https://kingulee.com/favicon.ico
  logoUrl: https://kingulee.com/favicon.ico
  theme: night
  name: Status
  introTitle: "Monitoring Website"
  introMessage: The monitoring **real-time** data from our [GitHub repository](https://github.com/King-Ulee/Status-Page-Advanced).
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.gg/VzUR95y

i18n:
  footer: This page is hosted on GitHub [King Ulee]($REPO) project since @2023-09-10, & created by [King Ulee](https://www.kingulee.com/).
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
